/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:d640a79e-38fc-4d48-a4be-56d0ee63f537",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_VHEvbhjcI",
    "aws_user_pools_web_client_id": "7t428k4qck5jjjmb03m0rj5n20",
    "oauth": {
        "domain": "nexttwampedf7287eff-f7287eff-dev.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/,https://main.dglnpqprxofv7.amplifyapp.com/",
        "redirectSignOut": "http://localhost:3000/,https://main.dglnpqprxofv7.amplifyapp.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
