/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:bb2b6ebf-888e-494c-9062-d78edb2ecee2",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_aHoYSyaQQ",
    "aws_user_pools_web_client_id": "3afgc1qafft2um0svngff8cvf9",
    "oauth": {
        "domain": "nexttwamped94038c14-94038c14-dev.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
